# Generated by Django 5.2.7 on 2026-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_xp',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='mission',
            name='ompleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
